<?xml version="1.0" encoding="utf-8"?><Database Name="LMS_Vishnu_Prakash" Class="LINQ_to_SQLDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=ggku4ser2;Initial Catalog=LMS_Vishnu_Prakash;User ID=SA" SettingsObjectName="Repository.Properties.Settings" SettingsPropertyName="LMS_Vishnu_PrakashConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.tbl_BookHistoryModel" Member="tbl_BookHistoryModels">
    <Type Name="tbl_BookHistoryModel">
      <Column Name="BookID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="UserID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="OperationPerformedAt" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="ReturnedAt" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Remarks" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="PerformedByID" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.tbl_BookModel" Member="tbl_BookModels">
    <Type Name="tbl_BookModel">
      <Column Name="BookID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="AuthorName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Department" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="IsActive" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="IsAvailable" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.tbl_UserModel" Member="tbl_UserModels">
    <Type Name="tbl_UserModel">
      <Column Name="UserID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Password" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="IsActive" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="IsAdmin" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
</Database>